import crypto from "node:crypto";
import { cookies } from "next/headers";
import { optionalEnv, requireEnv, isProduction, devBypassEnabled } from "./env";
const SESSION_COOKIE="nudge_session",OAUTH_STATE_COOKIE="nudge_oauth_state",PKCE_COOKIE="nudge_pkce_verifier",DEMO_COOKIE="nudge_demo";
export interface NudgeSession{email:string;name:string;picture?:string;accessToken:string;refreshToken?:string;expiresAt:number;spreadsheetId?:string;spreadsheetUrl?:string}
function keyFromSecret(){return crypto.createHash("sha256").update(requireEnv("AUTH_SECRET")).digest()} function b64url(buffer:Buffer){return buffer.toString("base64url")}
export function encryptSession(session:NudgeSession){const key=keyFromSecret(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",key,iv),plaintext=Buffer.from(JSON.stringify(session),"utf8"),encrypted=Buffer.concat([cipher.update(plaintext),cipher.final()]),tag=cipher.getAuthTag();return`${b64url(iv)}.${b64url(tag)}.${b64url(encrypted)}`}
export function decryptSession(value:string|undefined):NudgeSession|null{if(!value)return null;try{const[ivPart,tagPart,bodyPart]=value.split(".");if(!ivPart||!tagPart||!bodyPart)return null;const key=keyFromSecret(),decipher=crypto.createDecipheriv("aes-256-gcm",key,Buffer.from(ivPart,"base64url"));decipher.setAuthTag(Buffer.from(tagPart,"base64url"));const plain=Buffer.concat([decipher.update(Buffer.from(bodyPart,"base64url")),decipher.final()]);return JSON.parse(plain.toString("utf8")) as NudgeSession}catch{return null}}
export async function setSession(session:NudgeSession){const store=await cookies();store.set(SESSION_COOKIE,encryptSession(session),{httpOnly:true,secure:isProduction(),sameSite:"lax",path:"/",maxAge:60*60*24*30})}
export async function clearSession(){const store=await cookies();store.set(SESSION_COOKIE,"",{httpOnly:true,secure:isProduction(),sameSite:"lax",path:"/",maxAge:0});store.set(DEMO_COOKIE,"",{httpOnly:true,secure:isProduction(),sameSite:"lax",path:"/",maxAge:0})}
export async function setDemoSession(){const store=await cookies();store.set(DEMO_COOKIE,"1",{httpOnly:true,secure:isProduction(),sameSite:"lax",path:"/",maxAge:60*60*8})}
export async function getSession():Promise<NudgeSession|null>{if(devBypassEnabled())return{email:"demo@nudge.local",name:"Akanksha",accessToken:"demo",expiresAt:Date.now()+3600000,spreadsheetId:"demo",spreadsheetUrl:"#"};const store=await cookies();if(store.get(DEMO_COOKIE)?.value==="1")return{email:"demo@nudge.local",name:"Akanksha",accessToken:"demo",expiresAt:Date.now()+3600000,spreadsheetId:"demo",spreadsheetUrl:"#"};return decryptSession(store.get(SESSION_COOKIE)?.value)}
async function refreshGoogleToken(session:NudgeSession){if(!session.refreshToken)throw new Error("REAUTH_REQUIRED");const body=new URLSearchParams({client_id:requireEnv("GOOGLE_CLIENT_ID"),client_secret:requireEnv("GOOGLE_CLIENT_SECRET"),refresh_token:session.refreshToken,grant_type:"refresh_token"}),response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store"});if(!response.ok)throw new Error("REAUTH_REQUIRED");const json=await response.json() as{access_token:string;expires_in:number;refresh_token?:string},next={...session,accessToken:json.access_token,refreshToken:json.refresh_token||session.refreshToken,expiresAt:Date.now()+json.expires_in*1000};await setSession(next);return next}
export async function requireSession(){const session=await getSession();if(!session)throw new Error("UNAUTHORIZED");if(session.accessToken==="demo")return session;if(session.expiresAt<=Date.now()+60000)return refreshGoogleToken(session);return session}
export function createPkce(){const verifier=crypto.randomBytes(48).toString("base64url"),challenge=crypto.createHash("sha256").update(verifier).digest("base64url");return{verifier,challenge}} export function createOAuthState(){return crypto.randomBytes(24).toString("base64url")}
export async function storeOAuthTransient(state:string,verifier:string){const store=await cookies(),opts={httpOnly:true,secure:isProduction(),sameSite:"lax" as const,path:"/",maxAge:600};store.set(OAUTH_STATE_COOKIE,state,opts);store.set(PKCE_COOKIE,verifier,opts)}
export async function readOAuthTransient(){const store=await cookies();return{state:store.get(OAUTH_STATE_COOKIE)?.value,verifier:store.get(PKCE_COOKIE)?.value}} export async function clearOAuthTransient(){const store=await cookies();store.set(OAUTH_STATE_COOKIE,"",{path:"/",maxAge:0});store.set(PKCE_COOKIE,"",{path:"/",maxAge:0})}
export function googleAuthorizeUrl(origin:string,state:string,challenge:string){const url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.searchParams.set("client_id",requireEnv("GOOGLE_CLIENT_ID"));url.searchParams.set("redirect_uri",`${origin}/api/auth/google/callback`);url.searchParams.set("response_type","code");url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");url.searchParams.set("include_granted_scopes","true");url.searchParams.set("state",state);url.searchParams.set("code_challenge",challenge);url.searchParams.set("code_challenge_method","S256");url.searchParams.set("scope",["openid","email","profile","https://www.googleapis.com/auth/drive.file"].join(" "));return url.toString()}
export async function exchangeGoogleCode(origin:string,code:string,verifier:string){const body=new URLSearchParams({code,client_id:requireEnv("GOOGLE_CLIENT_ID"),client_secret:requireEnv("GOOGLE_CLIENT_SECRET"),redirect_uri:`${origin}/api/auth/google/callback`,grant_type:"authorization_code",code_verifier:verifier}),response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store"});if(!response.ok)throw new Error(`Google token exchange failed (${response.status}).`);return response.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number}>}
export async function fetchGoogleProfile(accessToken:string){const response=await fetch("https://openidconnect.googleapis.com/v1/userinfo",{headers:{authorization:`Bearer ${accessToken}`},cache:"no-store"});if(!response.ok)throw new Error("Could not read Google profile.");return response.json() as Promise<{email:string;name?:string;picture?:string}>}
export function isAllowedEmail(email:string){const allowed=optionalEnv("ALLOWED_EMAIL");return!allowed||email.toLowerCase()===allowed.toLowerCase()}
