"use client";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { PageState } from "@/components/PageState";
import { useNudgeData } from "@/lib/client/useNudgeData";
import { apiPost } from "@/lib/client/api";
import { indiaDateParts } from "@/lib/core/date";

const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;
interface Wrapped { year:number; theme:string; narrative:string; generatedAt:string; stats:{income:number;personalSpending:number;invested:number;saved:number;futureAllocation:number;topCategory:string|null;mostExpensiveMonth:string|null;lowestSpendMonth:string|null;movementDays:number;averageMood:number|null;checkInDays:number;journalDays:number;totalXp:number;coins:number;themeWords:string[]} }

export default function WrappedPage(){
 const now=new Date(); const india=indiaDateParts(now); const currentYear=india.year; const currentMonth=Number(india.month.slice(5)); const currentDay=Number(india.date.slice(8)); const initial=currentMonth===1?currentYear-1:currentYear; const [year,setYear]=useState(initial); const {data,loading,error,refresh}=useNudgeData(); const s=data?.snapshot; const [generated,setGenerated]=useState<Wrapped|null>(null); const [busy,setBusy]=useState(false); const [genError,setGenError]=useState("");
 const cached=useMemo(()=>{const row=data?.wrapped?.find(w=>Number(w.year)===year);if(!row)return null;try{return JSON.parse(row.json) as Wrapped}catch{return null}},[data,year]); const wrapped=generated?.year===year?generated:cached;
 async function generate(force=false){setBusy(true);setGenError("");try{const r=await apiPost<{wrapped:Wrapped}>("/api/wrapped",{year,force});setGenerated(r.wrapped);await refresh()}catch(e){setGenError(e instanceof Error?e.message:"Could not create Wrapped.")}finally{setBusy(false)}}
 useEffect(()=>{if(loading||wrapped||busy)return;const isDec31=currentMonth===12&&currentDay===31&&year===currentYear;const past=year<currentYear;if(isDec31||past)void generate(false)},[loading,year,wrapped]);
 return <AppShell name={s?.settings.display_name||"you"} spreadsheetUrl={data?.spreadsheetUrl} demo={data?.demo} onRefresh={refresh}><PageState loading={loading} error={error}>{s&&<>
  <div className="page-head"><div><span className="eyebrow">Your history, turned into perspective</span><h1>Nudge Wrapped.</h1><p>Numbers first, story second. No invented memories and no raw journal sent to AI by default.</p></div><label className="date-pill">Year&nbsp; <select value={year} onChange={e=>{setYear(Number(e.target.value));setGenerated(null)}} style={{border:0,padding:0,width:80,background:"transparent"}}>{Array.from({length:Math.max(1,currentYear-2025+1)},(_,i)=>currentYear-i).map(y=><option key={y}>{y}</option>)}</select></label></div>
  {wrapped?<section className="wrapped-shell"><div className="wrapped-intro"><span className="eyebrow" style={{color:"#f6d787"}}>Your {year} Wrapped</span><h2>{wrapped.theme}</h2><p>{year===currentYear&&currentMonth<12?"A year-so-far preview using only what you have recorded.":"Many small days became a bigger story."}</p></div><div className="wrapped-metrics"><div className="wrapped-metric"><strong>{money(wrapped.stats.personalSpending)}</strong><small>personal spending</small></div><div className="wrapped-metric"><strong>{money(wrapped.stats.futureAllocation)}</strong><small>saved + invested</small></div><div className="wrapped-metric"><strong>{wrapped.stats.checkInDays}</strong><small>check-in days</small></div><div className="wrapped-metric"><strong>{wrapped.stats.movementDays}</strong><small>movement days</small></div><div className="wrapped-metric"><strong>{wrapped.stats.topCategory||"—"}</strong><small>largest spending category</small></div><div className="wrapped-metric"><strong>{wrapped.stats.averageMood?`${wrapped.stats.averageMood.toFixed(1)}/5`:"—"}</strong><small>average recorded mood</small></div><div className="wrapped-metric"><strong>{wrapped.stats.totalXp.toLocaleString()}</strong><small>XP earned</small></div><div className="wrapped-metric"><strong>{wrapped.stats.journalDays}</strong><small>journal days</small></div></div><div className="wrapped-letter">{wrapped.narrative}</div><div className="wrapped-actions"><button className="secondary" onClick={()=>generate(true)} disabled={busy}>{busy?"Refreshing…":"Regenerate reflection"}</button></div></section>:<div className="empty-card"><span>✨</span><h3>{year===currentYear?"Your year is still unfolding.":`Ready to revisit ${year}?`}</h3><p>Wrapped uses your financial history, investing/saving totals, check-ins, rewards and privacy-safe journal themes. It never needs to invent what happened.</p><button className="primary" onClick={()=>generate(false)} disabled={busy}>{busy?"Gathering the year…":year===currentYear?"Preview my year so far":"Create my Wrapped"}</button>{genError&&<p className="form-error">{genError}</p>}</div>}
 </>}</PageState></AppShell>
}
