"use client";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { PageState } from "@/components/PageState";
import { useNudgeData } from "@/lib/client/useNudgeData";
import { apiPost } from "@/lib/client/api";
import { indiaDateParts } from "@/lib/core/date";

const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;
interface Wrapped { year:number; theme:string; narrative:string; generatedAt:string; stats:{income:number;personalSpending:number;invested:number;saved:number;futureAllocation:number;topCategory:string|null;mostExpensiveMonth:string|null;lowestSpendMonth:string|null;largestPurchase?:number;largestPurchaseLabel?:string|null;movementDays:number;averageMood:number|null;checkInDays:number;journalDays:number;totalXp:number;coins:number;comebackCount?:number;badgesUnlocked?:number;themeWords:string[]} }

export default function WrappedPage(){
 const now=new Date(); const india=indiaDateParts(now); const currentYear=india.year; const currentMonth=Number(india.month.slice(5)); const currentDay=Number(india.date.slice(8)); const initial=currentMonth===1?currentYear-1:currentYear; const [year,setYear]=useState(initial); const {data,loading,error,refresh}=useNudgeData(); const s=data?.snapshot; const [generated,setGenerated]=useState<Wrapped|null>(null); const [busy,setBusy]=useState(false); const [genError,setGenError]=useState("");
 const cached=useMemo(()=>{const row=data?.wrapped?.find(w=>Number(w.year)===year);if(!row)return null;try{return JSON.parse(row.json) as Wrapped}catch{return null}},[data,year]); const wrapped=generated?.year===year?generated:cached;
 async function generate(force=false){setBusy(true);setGenError("");try{const r=await apiPost<{wrapped:Wrapped}>("/api/wrapped",{year,force});setGenerated(r.wrapped);await refresh()}catch(e){setGenError(e instanceof Error?e.message:"Could not create Wrapped.")}finally{setBusy(false)}}
 useEffect(()=>{if(loading||wrapped||busy)return;const isDec31=currentMonth===12&&currentDay===31&&year===currentYear;const past=year<currentYear;if(isDec31||past)void generate(false)},[loading,year,wrapped,busy,currentMonth,currentDay,currentYear]);
 const personality=wrapped?spendingPersonality(wrapped):"";
 return <AppShell name={s?.settings.display_name||"you"} spreadsheetUrl={data?.spreadsheetUrl} demo={data?.demo} onRefresh={refresh}><PageState loading={loading} error={error}>{s&&<>
  <div className="page-head"><div><span className="eyebrow">Your history, turned into perspective</span><h1>Nudge Wrapped.</h1><p>Numbers first, story second. No invented memories and no raw journal sent to AI.</p></div><label className="date-pill">Year&nbsp; <select value={year} onChange={e=>{setYear(Number(e.target.value));setGenerated(null)}} style={{border:0,padding:0,width:80,background:"transparent"}}>{Array.from({length:Math.max(1,currentYear-2025+1)},(_,i)=>currentYear-i).map(y=><option key={y}>{y}</option>)}</select></label></div>
  {wrapped?<section className="wrapped-story">
   <article className="wrapped-chapter wrapped-cover"><span>01 · Your year</span><h2>{wrapped.theme}</h2><p>{year===currentYear&&currentMonth<12?"A year-so-far preview using only what you have recorded.":"Many small days became a bigger story."}</p><strong>{year}</strong></article>
   <article className="wrapped-chapter money-chapter"><span>02 · Money</span><h2>{money(wrapped.stats.personalSpending)}</h2><p>personal spending recorded</p><div className="wrapped-duo"><b>{money(wrapped.stats.income)}<small>income</small></b><b>{wrapped.stats.topCategory||"—"}<small>largest category</small></b></div>{wrapped.stats.largestPurchase? <p className="wrapped-footnote">Largest recorded personal purchase: <b>{money(wrapped.stats.largestPurchase)}</b>{wrapped.stats.largestPurchaseLabel?` · ${wrapped.stats.largestPurchaseLabel}`:""}</p>:null}</article>
   <article className="wrapped-chapter future-chapter"><span>03 · Future You</span><h2>{money(wrapped.stats.futureAllocation)}</h2><p>went toward savings + investments</p><div className="wrapped-duo"><b>{money(wrapped.stats.saved)}<small>saved</small></b><b>{money(wrapped.stats.invested)}<small>invested</small></b></div></article>
   <article className="wrapped-chapter personality-chapter"><span>04 · Spending personality</span><h2>{personality}</h2><p>{wrapped.stats.mostExpensiveMonth?`${wrapped.stats.mostExpensiveMonth} was your fullest spending month.`:"Your spending story is still taking shape."}</p>{wrapped.stats.lowestSpendMonth&&<small>Your lightest recorded spending month was {wrapped.stats.lowestSpendMonth}.</small>}</article>
   <article className="wrapped-chapter life-chapter"><span>05 · Life signals</span><h2>{wrapped.stats.movementDays} movement days</h2><div className="wrapped-duo"><b>{wrapped.stats.averageMood?`${wrapped.stats.averageMood.toFixed(1)}/5`:"—"}<small>average recorded mood</small></b><b>{wrapped.stats.checkInDays}<small>check-in days</small></b></div><p>{wrapped.stats.journalDays} days held a journal memory.</p></article>
   <article className="wrapped-chapter comeback-chapter"><span>06 · Returning counts</span><h2>{wrapped.stats.comebackCount||0} comebacks</h2><p>A gap never erased the plant. Every return continued the same story.</p><div className="wrapped-duo"><b>{wrapped.stats.totalXp.toLocaleString()}<small>XP earned</small></b><b>{wrapped.stats.badgesUnlocked||0}<small>badges recorded</small></b></div></article>
   <article className="wrapped-chapter words-chapter"><span>07 · Little themes</span><h2>{wrapped.stats.themeWords.length?wrapped.stats.themeWords.slice(0,3).join(" · "):"Your words stayed yours."}</h2><p>Nudge derives these locally from your saved journal text; the raw entries are not sent to AI.</p></article>
   <article className="wrapped-chapter letter-chapter"><span>08 · Letter to Future You</span><div className="wrapped-letter">{wrapped.narrative}</div></article>
   <article className="wrapped-chapter wrapped-final"><span>09 · The question</span><h2>What kind of year did I live?</h2><p>{wrapped.theme} is one lens—not a grade. The fuller answer belongs to you.</p><button className="secondary" onClick={()=>generate(true)} disabled={busy}>{busy?"Refreshing…":"Refresh this reflection"}</button></article>
  </section>:<div className="empty-card"><span>✨</span><h3>{year===currentYear?"Your year is still unfolding.":`Ready to revisit ${year}?`}</h3><p>Wrapped uses your financial history, investing/saving totals, check-ins, rewards and privacy-safe journal themes. It never needs to invent what happened.</p><button className="primary" onClick={()=>generate(false)} disabled={busy}>{busy?"Gathering the year…":year===currentYear?"Preview my year so far":"Create my Wrapped"}</button>{genError&&<p className="form-error">{genError}</p>}</div>}
 </>}</PageState></AppShell>
}

function spendingPersonality(w:Wrapped){const cat=w.stats.topCategory;if(!cat)return"Still unfolding";if(cat==="Travel")return"The Experience Explorer";if(cat==="Food")return"The Table & Togetherness Year";if(cat==="Learning")return"The Curious Builder";if(cat==="Gifts")return"The Generous Heart";if(cat==="Shopping")return"The Taste Curator";return`The ${cat} Chapter`}
