"use client";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { PageState } from "@/components/PageState";
import { PlantLifecycle, PlantVisual } from "@/components/PlantVisual";
import { useNudgeData } from "@/lib/client/useNudgeData";
import { apiPost } from "@/lib/client/api";

type ShopItem={id:string;icon:string;name:string;cost:number};
export default function RewardsPage(){
 const {data,loading,error,refresh}=useNudgeData(); const s=data?.snapshot; const coins=s?.rewards.reduce((a,r)=>a+Number(r.coins||0),0)||0; const nextLevel=s?Math.ceil((s.growth.totalXp+1)/250)*250:250; const xpInto=s?s.growth.totalXp-(s.growth.level-1)*250:0;
 const badges=s?[{icon:"🌱",name:"First Growth",desc:"Your Nudge journey has begun.",ok:s.growth.totalXp>0},{icon:"🔥",name:"Momentum Maker",desc:"Strong recent check-in rhythm.",ok:s.growth.momentum==="strong"},{icon:"🌿",name:"Comeback",desc:"Returning after a break counts.",ok:s.rewards.some(r=>r.action==="comeback")},{icon:"💰",name:"Money Aware",desc:"Logged spending with intention.",ok:s.rewards.filter(r=>r.action==="expense_logged").length>=5},{icon:"🪴",name:"Future You",desc:"Investing habit recorded.",ok:s.investments.length>0},{icon:"✎",name:"Reflection",desc:"Kept meaningful moments.",ok:s.journal.length>=2},{icon:"🛡️",name:"Goal Builder",desc:"A money goal is in motion.",ok:s.goals.some(g=>g.current_amount>0)},{icon:"☀️",name:"Showing Up",desc:"Ten daily check-ins recorded.",ok:s.checkIns.length>=10}]:[];
 const[shop,setShop]=useState<ShopItem[]>([]);const[name,setName]=useState("");const[cost,setCost]=useState("");const[icon,setIcon]=useState("✨");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/rewards/shop").then(r=>r.json()).then(j=>Array.isArray(j.items)&&setShop(j.items)).catch(()=>undefined)},[]);
 async function saveShop(items:ShopItem[]){setBusy(true);setMessage("");try{const r=await apiPost<{items:ShopItem[]}>("/api/rewards/shop",{action:"save",items});setShop(r.items);setMessage("Reward shelf saved. 🌿")}catch(e){setMessage(e instanceof Error?e.message:"Could not save rewards.")}finally{setBusy(false)}}
 async function add(e:FormEvent){e.preventDefault();const c=Number(cost);if(!name.trim()||!Number.isFinite(c)||c<=0)return;const item={id:crypto.randomUUID(),icon:icon||"✨",name:name.trim(),cost:Math.round(c)};await saveShop([...shop,item]);setName("");setCost("");}
 async function redeem(item:ShopItem){setBusy(true);setMessage("");try{await apiPost("/api/rewards/shop",{action:"redeem",item});setMessage(`${item.icon} ${item.name} redeemed. Enjoy it without guilt.`);await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Could not redeem.")}finally{setBusy(false)}}
 return <AppShell name={s?.settings.display_name||"you"} spreadsheetUrl={data?.spreadsheetUrl} demo={data?.demo} onRefresh={refresh}><PageState loading={loading} error={error}>{s&&<>
  <div className="page-head"><div><span className="eyebrow">Reward growth, not pressure</span><h1>Your progress has roots.</h1><p>XP remembers the lifetime journey. Momentum is allowed to change.</p></div><span className="date-pill">🪙 {coins.toLocaleString()} Quest Coins</span></div>
  <section className="card reward-hero"><div style={{textAlign:"center"}}><PlantVisual stage={s.growth.plantStage} resting={s.growth.momentum==="resting"}/></div><div><span className="eyebrow">Level {s.growth.level}</span><h2 style={{fontSize:34,margin:"5px 0"}}>Your {s.growth.plantStage} keeps its history.</h2><p className="helper">Missing days never send you back to Seed. A quieter period becomes “resting”; returning creates new growth.</p><div className="xp-line"><span style={{width:`${Math.min(100,(xpInto/250)*100)}%`}}/></div><small>{s.growth.totalXp.toLocaleString()} XP · next level at {nextLevel.toLocaleString()} XP</small><div style={{marginTop:26}}><PlantLifecycle current={s.growth.plantStage}/></div></div></section>
  <div className="spacer-18"/>
  <div className="reward-stats"><div className="reward-stat"><strong>{s.growth.totalXp.toLocaleString()}</strong><small>Total XP</small></div><div className="reward-stat"><strong>{coins.toLocaleString()}</strong><small>Quest Coins</small></div><div className="reward-stat"><strong>{badges.filter(b=>b.ok).length}/{badges.length}</strong><small>Badges unlocked</small></div></div>
  <div className="spacer-18"/>
  <section className="card"><div className="section-title"><h2>Badges that mean something</h2><span>Comebacks matter too</span></div><div className="badge-grid">{badges.map(b=><article className="badge" key={b.name} style={{opacity:b.ok?1:.38}}><div className="badge-icon">{b.icon}</div><h4>{b.name}</h4><p>{b.ok?b.desc:"Still growing toward this."}</p></article>)}</div></section>
  <div className="spacer-18"/>
  <section className="card"><div className="section-title"><h2>Your reward shelf</h2><span>You decide what feels worth celebrating</span></div><div className="reward-shop">{shop.map(item=><div className="reward-item" key={item.id}><span>{item.icon}</span><b>{item.name}</b><small>{item.cost} coins</small><button className="mini-button" disabled={busy||coins<item.cost} onClick={()=>redeem(item)}>{coins>=item.cost?"Redeem":"Keep growing"}</button></div>)}</div><form className="reward-create" onSubmit={add}><input aria-label="Reward icon" value={icon} onChange={e=>setIcon(e.target.value)} maxLength={4}/><input aria-label="Reward name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your own reward"/><input aria-label="Reward cost" inputMode="numeric" value={cost} onChange={e=>setCost(e.target.value)} placeholder="Coins"/><button className="secondary" disabled={busy}>Add reward</button></form>{message&&<p className="helper">{message}</p>}<p className="helper" style={{marginTop:14}}>Quest Coins are playful markers, not permission slips. You are allowed rest and joy regardless of your balance.</p></section>
 </>}</PageState></AppShell>
}
