"use client";
import { FormEvent, useEffect, useState } from "react";
import { Logo } from "@/components/Logo";
import { apiPost } from "@/lib/client/api";

export default function SetupPage(){
 const [step,setStep]=useState(1); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [checking,setChecking]=useState(true);
 const [name,setName]=useState(""); const [income,setIncome]=useState(""); const [essential,setEssential]=useState("");
 const [horizon,setHorizon]=useState("long"); const [comfort,setComfort]=useState("medium"); const [priority,setPriority]=useState("balanced");
 useEffect(()=>{let live=true;fetch("/api/snapshot",{cache:"no-store"}).then(async r=>{if(r.status===401){window.location.href="/";return null}return r.json()}).then(j=>{if(!live||!j)return;if(j.snapshot?.settings?.onboarding_complete==="true"){window.location.replace("/dashboard");return}setName(j.snapshot?.settings?.display_name||"");setChecking(false)}).catch(()=>live&&setChecking(false));return()=>{live=false}},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await apiPost("/api/settings",{display_name:name,monthly_income_target:Number(income||0),essential_expenses:Number(essential||0),horizon,volatilityComfort:comfort,priority,onboarding_complete:true});window.location.href="/dashboard"}catch(e){setError(e instanceof Error?e.message:"Setup failed.")}finally{setBusy(false)}};
 if(checking)return <main className="setup-page"><div className="setup-card"><Logo/><div className="loading"><span className="loading-seed">🌱</span><p>Finding your Nudge…</p></div></div></main>;
 return <main className="setup-page"><div className="setup-card"><Logo/><div className="setup-progress"><span style={{width:`${step*33.33}%`}}/></div>{step===1&&<section><span className="eyebrow">1 of 3 · your basics</span><h1>Make Nudge yours.</h1><p>Only the numbers Nudge needs for useful context. You can change them later.</p><label>What should Nudge call you?<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><div className="field-row"><label>Typical monthly income ₹<input inputMode="decimal" value={income} onChange={e=>setIncome(e.target.value)} placeholder="Optional"/></label><label>Essential monthly expenses ₹<input inputMode="decimal" value={essential} onChange={e=>setEssential(e.target.value)} placeholder="Optional"/></label></div><button className="primary wide" onClick={()=>setStep(2)}>Continue →</button></section>}{step===2&&<section><span className="eyebrow">2 of 3 · investing mindset</span><h1>Your investor profile.</h1><p>This is an educational profile for context—not personalized investment advice.</p><label>Investment horizon<select value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="short">Under 3 years</option><option value="medium">3–7 years</option><option value="long">7+ years</option></select></label><label>How do temporary market falls feel?<select value={comfort} onChange={e=>setComfort(e.target.value)}><option value="low">I prefer stability</option><option value="medium">I can tolerate some ups and downs</option><option value="high">I accept larger fluctuations for long-term growth</option></select></label><label>Main priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="preserve">Protect capital</option><option value="balanced">Balance stability and growth</option><option value="growth">Long-term growth</option></select></label><div className="button-row"><button className="secondary" onClick={()=>setStep(1)}>Back</button><button className="primary" onClick={()=>setStep(3)}>Continue →</button></div></section>}{step===3&&<form onSubmit={submit}><span className="eyebrow">3 of 3 · the philosophy</span><h1>Your Nudge starts as a seed. 🌱</h1><p>You’ll grow through <b>Seed → Sprout → Seedling → Plant</b> as you build lifetime XP. Missing days never erase the plant; quieter stretches simply become a resting season.</p><div className="setup-beliefs"><span>💛 No shame</span><span>🌿 Comebacks count</span><span>💰 Money stays in your Sheet</span><span>🪴 Investing stays educational</span></div>{error&&<p className="form-error">{error}</p>}<div className="button-row"><button type="button" className="secondary" onClick={()=>setStep(2)}>Back</button><button className="primary" disabled={busy}>{busy?"Creating your Nudge…":"Enter Nudge →"}</button></div></form>}</div></main>
}
