"use client";
import { FormEvent, useState } from "react";
import { apiPost } from "@/lib/client/api";
import { queueOffline } from "@/lib/client/offline";
import { equalSplit } from "@/lib/core/splits";

type Tab = "money" | "investment" | "checkin" | "journal";
const categories = ["Food", "Travel", "Shopping", "Living", "Bills", "Fun", "Health", "Learning", "Gifts", "Other"];
const paymentMethods = ["UPI", "Card", "Cash", "Bank transfer", "Wallet", "Other"];

interface FormProps { busy: boolean; setBusy: (value:boolean)=>void; setError:(value:string)=>void; finish:(message:string)=>void }

export function QuickAddModal({ onClose, onSaved }: { onClose: () => void; onSaved: (message: string) => void }) {
 const [tab,setTab]=useState<Tab>("money"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const finish=(message:string)=>{onSaved(message);onClose()}; const props={busy,setBusy,setError,finish};
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal-card" role="dialog" aria-modal="true" aria-label="Quick add"><div className="modal-head"><div><span className="eyebrow">Quick add</span><h2>One small update</h2></div><button onClick={onClose} aria-label="Close">×</button></div><div className="segmented">{(["money","investment","checkin","journal"] as Tab[]).map(t=><button key={t} className={tab===t?"selected":""} onClick={()=>{setTab(t);setError("")}}>{t==="money"?"💸 Money":t==="investment"?"🌱 Invest":t==="checkin"?"☀ Check-in":"✎ Journal"}</button>)}</div>{tab==="money"&&<MoneyForm {...props}/>} {tab==="investment"&&<InvestmentForm {...props}/>} {tab==="checkin"&&<CheckinForm {...props}/>} {tab==="journal"&&<JournalForm {...props}/>} {error&&<p className="form-error">{error}</p>}</section></div>
}

function MoneyForm({busy,setBusy,setError,finish}:FormProps){
 const [type,setType]=useState("expense"),[amount,setAmount]=useState(""),[category,setCategory]=useState("Food"),[description,setDescription]=useState(""),[needWant,setNeedWant]=useState("neutral"),[merchant,setMerchant]=useState(""),[payment,setPayment]=useState("UPI"),[tag,setTag]=useState(""),[split,setSplit]=useState(false); const [friends,setFriends]=useState<Array<{person:string;amount:string}>>([]);
 const equalize=()=>{const names=friends.map(f=>f.person.trim()).filter(Boolean),total=Number(amount);if(!names.length||!total)return;const result=equalSplit(total,names);let i=0;setFriends(friends.map(f=>f.person.trim()?{...f,amount:String(result.shares[i++]?.amount??"")}:f))};
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");const body={client_id:crypto.randomUUID().replaceAll("-",""),type,amount:Number(amount),category,description,merchant,payment_method:payment,event_tag:tag,need_or_want:needWant,splits:type==="expense"&&split?friends.filter(f=>f.person.trim()).map(f=>({person:f.person.trim(),amount:Number(f.amount)})):[]};try{await apiPost("/api/transactions",body);finish(type==="expense"?"Money logged — awareness, not judgment. 🌿":"Money update saved. 🌱")}catch(err){if(!navigator.onLine||err instanceof TypeError){await queueOffline("/api/transactions",body);finish("Saved offline. Nudge will sync when you are connected. ☁️")}else setError(err instanceof Error?err.message:"Could not save.")}finally{setBusy(false)}};
 return <form className="form-stack" onSubmit={submit}><div className="field-row"><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="expense">Expense</option><option value="income">Income</option><option value="saving">Savings transfer</option><option value="transfer">Account transfer</option><option value="refund">Refund</option></select></label><label>Amount ₹<input inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label></div>{(type==="expense"||type==="refund")&&<><div><span className="field-label">Category</span><div className="chip-grid">{categories.map(c=><button type="button" key={c} className={category===c?"chip chosen":"chip"} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><label>Description <input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Lunch, auto, groceries…"/></label>{type==="expense"&&<div><span className="field-label">How did it feel?</span><div className="choice-row">{[["need","Need"],["neutral","Neutral"],["want","Want"]].map(([v,l])=><button type="button" key={v} className={needWant===v?"choice chosen":"choice"} onClick={()=>setNeedWant(v)}>{l}</button>)}</div></div>}{type==="expense"&&<label className="toggle-line"><input type="checkbox" checked={split} onChange={e=>{setSplit(e.target.checked);if(e.target.checked&&!friends.length)setFriends([{person:"",amount:""}])}}/> Split with friends</label>}{type==="expense"&&split&&<div className="split-box"><div className="split-head"><span>Friends owe you</span><button type="button" onClick={equalize}>Split equally</button></div>{friends.map((f,i)=><div className="friend-row" key={i}><input placeholder="Name" value={f.person} onChange={e=>setFriends(friends.map((x,j)=>j===i?{...x,person:e.target.value}:x))}/><input placeholder="₹ owed" inputMode="decimal" value={f.amount} onChange={e=>setFriends(friends.map((x,j)=>j===i?{...x,amount:e.target.value}:x))}/><button type="button" onClick={()=>setFriends(friends.filter((_,j)=>j!==i))}>×</button></div>)}<button type="button" className="text-action" onClick={()=>setFriends([...friends,{person:"",amount:""}])}>＋ Add friend</button></div>}</>}{type!=="expense"&&type!=="refund"&&<label>Note <input value={description} onChange={e=>setDescription(e.target.value)}/></label>}<details className="more-details"><summary>Optional details</summary><div className="field-row"><label>Payment method<select value={payment} onChange={e=>setPayment(e.target.value)}>{paymentMethods.map(m=><option key={m}>{m}</option>)}</select></label><label>Merchant / place<input value={merchant} onChange={e=>setMerchant(e.target.value)}/></label></div><label>Tag<input value={tag} onChange={e=>setTag(e.target.value)}/></label></details><button className="primary wide" disabled={busy}>{busy?"Saving…":"Save"}</button></form>
}
function InvestmentForm({busy,setBusy,setError,finish}:FormProps){const[name,setName]=useState(""),[type,setType]=useState("Mutual Fund"),[amount,setAmount]=useState(""),[value,setValue]=useState(""),[kind,setKind]=useState("sip");const valuation=kind==="valuation";const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await apiPost("/api/investments",{asset_name:name,asset_type:type,amount_invested:valuation?0:Number(amount),current_value:value?Number(value):undefined,transaction_type:kind});finish(valuation?"Portfolio value refreshed. 🌿":"Future You got a little more support. 🌱")}catch(e){setError(e instanceof Error?e.message:"Could not save.")}finally{setBusy(false)}};return <form className="form-stack" onSubmit={submit}><label>Investment name<input required value={name} onChange={e=>setName(e.target.value)}/></label><div className="field-row"><label>Asset type<select value={type} onChange={e=>setType(e.target.value)}><option>Mutual Fund</option><option>Stocks</option><option>ETF</option><option>RD / FD</option><option>PPF</option><option>Gold</option><option>NPS</option><option>Other</option></select></label><label>Action<select value={kind} onChange={e=>setKind(e.target.value)}><option value="sip">SIP</option><option value="buy">Buy</option><option value="deposit">Deposit</option><option value="sell">Sell</option><option value="withdrawal">Withdrawal</option><option value="valuation">Update current value</option></select></label></div>{!valuation&&<label>Transaction amount ₹<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}<label>{valuation?"Current total holding value ₹":"Current total holding value ₹ (optional)"}<input required={valuation} inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)}/></label><p className="helper">Current value means the value of the whole named holding after this action.</p><button className="primary wide" disabled={busy}>{busy?"Saving…":valuation?"Refresh value":"Plant this investment"}</button></form>}
function CheckinForm({busy,setBusy,setError,finish}:FormProps){const[mood,setMood]=useState(4),[energy,setEnergy]=useState(4),[move,setMove]=useState("30"),[food,setFood]=useState("mindful"),[intention,setIntention]=useState(""),[enjoyed,setEnjoyed]=useState(""),[proud,setProud]=useState(""),[reflection,setReflection]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await apiPost<{message?:string}>("/api/checkins",{mood,energy,movement_minutes:Number(move||0),food_feeling:food,today_intention:intention,something_enjoyed:enjoyed,proud_of_today:proud,reflection});finish(r.message||"Check-in saved. 🌿")}catch(e){setError(e instanceof Error?e.message:"Could not save.")}finally{setBusy(false)}};return <form className="form-stack" onSubmit={submit}><div><span className="field-label">How are you feeling?</span><div className="mood-row">{[1,2,3,4,5].map(n=><button type="button" key={n} className={mood===n?"mood chosen":"mood"} onClick={()=>setMood(n)}>{["😞","😕","😐","🙂","😊"][n-1]}</button>)}</div></div><div className="field-row"><label>Energy<select value={energy} onChange={e=>setEnergy(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label>Movement (minutes)<input value={move} onChange={e=>setMove(e.target.value)}/></label></div><label>Food today<select value={food} onChange={e=>setFood(e.target.value)}><option value="mindful">Mindful</option><option value="okay">Okay</option><option value="indulgent">Indulgent / enjoyed something</option><option value="not_sure">Not sure</option></select></label><label>Today’s intention / motto<input value={intention} onChange={e=>setIntention(e.target.value)}/></label><label>Something you enjoyed<input value={enjoyed} onChange={e=>setEnjoyed(e.target.value)}/></label><label>Something you are proud of<input value={proud} onChange={e=>setProud(e.target.value)}/></label><label>One line about today<textarea rows={2} value={reflection} onChange={e=>setReflection(e.target.value)}/></label><button className="primary wide" disabled={busy}>{busy?"Saving…":"Save check-in"}</button></form>}
function JournalForm({busy,setBusy,setError,finish}:FormProps){const[type,setType]=useState("journal"),[content,setContent]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await apiPost("/api/journal",{entry_type:type,content});finish("Saved. You do not need many words for a moment to matter. 💛")}catch(e){setError(e instanceof Error?e.message:"Could not save.")}finally{setBusy(false)}};return <form className="form-stack" onSubmit={submit}><div className="choice-row">{[["journal","Journal"],["gratitude","Gratitude"],["quick_memory","Memory"],["moment","Moment"]].map(([v,l])=><button type="button" key={v} className={type===v?"choice chosen":"choice"} onClick={()=>setType(v)}>{l}</button>)}</div><label>What do you want to remember?<textarea required rows={6} value={content} onChange={e=>setContent(e.target.value)}/></label><button className="primary wide" disabled={busy}>{busy?"Saving…":"Keep this moment"}</button></form>}
