import type { Budget, DailyCheckIn, Goal, Investment, JournalEntry, RewardEvent, SettingsMap, Split, Transaction } from "./types.js";

const iso = (day: number) => `2026-09-${String(day).padStart(2, "0")}`;
const august = (day: number) => `2026-08-${String(day).padStart(2, "0")}`;

export const demoSettings: SettingsMap = { schema_version:"1", currency:"INR", onboarding_complete:"true", display_name:"Akanksha", monthly_income_target:"72000", essential_expenses:"30000", investor_profile:"Balanced Builder", risk_comfort:"Moderate", investment_horizon:"Long term" };
export const demoTransactions: Transaction[] = [
  {id:"t1",date:iso(1),type:"income",amount:72000,category:"Income",description:"Monthly income"},{id:"t2",date:iso(1),type:"investment",amount:6000,category:"Investment",description:"Index fund SIP"},{id:"t3",date:iso(2),type:"expense",amount:380,category:"Food",description:"Lunch",need_or_want:"need"},{id:"t4",date:iso(2),type:"expense",amount:240,category:"Travel",description:"Commute",need_or_want:"need"},{id:"t5",date:iso(3),type:"expense",amount:1200,personal_amount:400,split_amount:800,category:"Food",description:"Dinner with friends",need_or_want:"want"},{id:"t6",date:iso(4),type:"expense",amount:899,category:"Shopping",description:"Desk organiser",need_or_want:"want"},{id:"t7",date:iso(5),type:"saving",amount:5000,category:"Savings",description:"Emergency fund",goal_id:"g1"},{id:"t8",date:iso(5),type:"expense",amount:260,category:"Travel",description:"Metro + auto",need_or_want:"need"},{id:"t9",date:iso(6),type:"expense",amount:560,category:"Food",description:"Weekend brunch",need_or_want:"want"},{id:"a1",date:august(1),type:"income",amount:72000,category:"Income",description:"Monthly income"},{id:"a2",date:august(2),type:"investment",amount:6000,category:"Investment",description:"Index fund SIP"},{id:"a3",date:august(3),type:"expense",amount:4200,category:"Food",description:"Food total sample",need_or_want:"neutral"},{id:"a4",date:august(8),type:"expense",amount:3100,category:"Travel",description:"Travel total sample",need_or_want:"neutral"},{id:"a5",date:august(15),type:"expense",amount:2500,category:"Shopping",description:"Shopping total sample",need_or_want:"want"},{id:"a6",date:august(20),type:"saving",amount:5000,category:"Savings",description:"Emergency fund",goal_id:"g1"}
];
export const demoSplits: Split[]=[{id:"s1",transaction_id:"t5",person:"Riya",total_bill:1200,my_share:400,their_share:400,status:"pending",settled_amount:0},{id:"s2",transaction_id:"t5",person:"Neha",total_bill:1200,my_share:400,their_share:400,status:"partial",settled_amount:100}];
export const demoInvestments: Investment[]=[{id:"i1",date:"2026-06-01",asset_name:"Broad Market Index",asset_type:"Mutual Fund",transaction_type:"sip",amount_invested:6000,current_value:25000},{id:"i2",date:"2026-07-01",asset_name:"Broad Market Index",asset_type:"Mutual Fund",transaction_type:"sip",amount_invested:6000,current_value:25000},{id:"i3",date:"2026-08-01",asset_name:"Broad Market Index",asset_type:"Mutual Fund",transaction_type:"sip",amount_invested:6000,current_value:25000},{id:"i4",date:"2026-09-01",asset_name:"Broad Market Index",asset_type:"Mutual Fund",transaction_type:"sip",amount_invested:6000,current_value:25000},{id:"i5",date:"2026-05-10",asset_name:"Bluechip Basket",asset_type:"Stocks",transaction_type:"buy",amount_invested:18000,current_value:19650},{id:"i6",date:"2026-03-01",asset_name:"Recurring Deposit",asset_type:"RD / FD",transaction_type:"deposit",amount_invested:30000,current_value:30900}];
export const demoGoals: Goal[]=[{id:"g1",goal:"Emergency Fund",goal_type:"Safety",target_amount:200000,current_amount:145000,monthly_target:5000,priority:"High",status:"active"},{id:"g2",goal:"Japan Trip",goal_type:"Experience",target_amount:200000,current_amount:124000,target_date:"2027-04-30",monthly_target:12000,priority:"Medium",status:"active"},{id:"g3",goal:"Future Learning",goal_type:"Learning",target_amount:100000,current_amount:28000,monthly_target:4000,priority:"Medium",status:"active"}];
export const demoBudgets: Budget[]=[{id:"b1",month:"2026-09",category:"Food",budget_amount:9000},{id:"b2",month:"2026-09",category:"Travel",budget_amount:5000},{id:"b3",month:"2026-09",category:"Shopping",budget_amount:4000}];
export const demoCheckIns: DailyCheckIn[]=[1,2,3,4,5,6].map(d=>({id:`c${d}`,date:iso(d),mood:d===4?3:4,energy:d%2?4:3,movement_minutes:d===3?0:30,movement_type:d===3?"Rest":"Walk / workout",food_feeling:d===6?"indulgent":"mindful",today_intention:"Move calmly and make one intentional choice.",proud_of_today:"I showed up for myself.",reflection:d%2?"A balanced day.":"A busy day, but I found a small reset."}));
export const demoJournal: JournalEntry[]=[{id:"j1",date:iso(2),entry_type:"gratitude",content:"Grateful for a relaxed dinner, good conversation and a calm walk."},{id:"j2",date:iso(5),entry_type:"quick_memory",content:"A productive day followed by music and time with friends."}];
export const demoRewards: RewardEvent[]=[...[1,2,3,4,5,6].map(d=>({id:`r-c-${d}`,date:iso(d),action:"checkin_completed",xp:20,coins:10})),...[2,3,4,5,6].map(d=>({id:`r-e-${d}`,date:iso(d),action:"expense_logged",xp:5,coins:2})),{id:"r-i-1",date:iso(1),action:"investment_added",xp:15,coins:8},{id:"r-j-1",date:iso(2),action:"journal_written",xp:10,coins:5},{id:"r-j-2",date:iso(5),action:"journal_written",xp:10,coins:5},{id:"r-old",date:"2026-08-25",action:"legacy_progress",xp:620,coins:260}];
export const demoData={settings:demoSettings,transactions:demoTransactions,splits:demoSplits,investments:demoInvestments,goals:demoGoals,budgets:demoBudgets,checkIns:demoCheckIns,journal:demoJournal,rewards:demoRewards,wrapped:[] as Array<{year:string;json:string;generated_at:string}>};
