import type { FinanceSummary, Investment, InvestmentAssetSummary, Split, Transaction } from "./types.js";

const safeNumber = (value: number | undefined) => Number.isFinite(value) ? Number(value) : 0;

export function monthKey(date: string): string { return date.slice(0, 7); }
export function previousMonthKey(month: string): string { const [y,m]=month.split("-").map(Number); const d=new Date(Date.UTC(y,m-1,1)); d.setUTCMonth(d.getUTCMonth()-1); return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`; }
export function personalAmount(tx: Transaction): number { if(tx.type!=="expense") return safeNumber(tx.amount); return tx.personal_amount==null?safeNumber(tx.amount):safeNumber(tx.personal_amount); }

export function buildFinanceSummary(month:string,transactions:Transaction[],splits:Split[],today=new Date()):FinanceSummary {
 const monthTx=transactions.filter(t=>monthKey(t.date)===month); const income=monthTx.filter(t=>t.type==="income").reduce((s,t)=>s+safeNumber(t.amount),0); const expenseTx=monthTx.filter(t=>t.type==="expense"); const refundTx=monthTx.filter(t=>t.type==="refund"); const grossPersonalSpending=expenseTx.reduce((s,t)=>s+personalAmount(t),0); const refundTotal=refundTx.reduce((s,t)=>s+safeNumber(t.amount),0); const personalSpending=grossPersonalSpending-refundTotal; const cashOutflow=monthTx.filter(t=>["expense","investment","saving","transfer"].includes(t.type)).reduce((s,t)=>s+safeNumber(t.amount),0); const invested=monthTx.filter(t=>t.type==="investment").reduce((s,t)=>s+safeNumber(t.amount),0); const saved=monthTx.filter(t=>t.type==="saving").reduce((s,t)=>s+safeNumber(t.amount),0); const futureAllocation=invested+saved; const cashLeft=income-personalSpending-futureAllocation; const categoryTotals:Record<string,number>={};
 for(const tx of expenseTx){const c=tx.category||"Other";categoryTotals[c]=(categoryTotals[c]||0)+personalAmount(tx)} for(const tx of refundTx){const c=tx.category||"Refund";categoryTotals[c]=(categoryTotals[c]||0)-safeNumber(tx.amount)} const sortedCategories=Object.entries(categoryTotals).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]); const needTotal=expenseTx.filter(t=>t.need_or_want==="need").reduce((s,t)=>s+personalAmount(t),0); const wantTotal=expenseTx.filter(t=>t.need_or_want==="want").reduce((s,t)=>s+personalAmount(t),0); const txIds=new Set(monthTx.map(t=>t.id)); const receivable=splits.filter(s=>txIds.has(s.transaction_id)&&s.status!=="settled").reduce((sum,s)=>sum+Math.max(0,safeNumber(s.their_share)-safeNumber(s.settled_amount)),0);
 const [year,monthNum]=month.split("-").map(Number); const isCurrentMonth=year===today.getUTCFullYear()&&monthNum===today.getUTCMonth()+1; const endDay=isCurrentMonth?today.getUTCDate():new Date(Date.UTC(year,monthNum,0)).getUTCDate(); const expenseDates=new Set(expenseTx.filter(t=>personalAmount(t)>0).map(t=>t.date)); let noSpendDays=0; for(let d=1;d<=endDay;d++){if(!expenseDates.has(`${month}-${String(d).padStart(2,"0")}`))noSpendDays++}
 return {period:month,income,personalSpending,cashOutflow,invested,saved,futureAllocation,cashLeft,savingsRate:income>0?(saved/income)*100:0,investmentRate:income>0?(invested/income)*100:0,futureRate:income>0?(futureAllocation/income)*100:0,receivable,topCategory:sortedCategories[0]?.[0]??null,topCategoryAmount:sortedCategories[0]?.[1]??0,categoryTotals,needTotal,wantTotal,noSpendDays,transactionCount:monthTx.length};
}

export function buildInvestmentSummary(investments:Investment[]){const groups=new Map<string,Investment[]>();for(const inv of investments){const key=`${inv.asset_type||"Other"}::${inv.asset_name||"Unnamed holding"}`;const rows=groups.get(key)||[];rows.push(inv);groups.set(key,rows)}const assets:InvestmentAssetSummary[]=[];for(const[,rawRows]of groups.entries()){const rows=[...rawRows].sort((a,b)=>`${a.date}${a.created_at||""}`.localeCompare(`${b.date}${b.created_at||""}`));const name=rawRows[0]?.asset_name||"Unnamed holding";let invested=0,estimatedValue=0,hasExplicitValue=false,type=rows[0]?.asset_type||"Other",lastUpdated=rows[0]?.date||"";for(const row of rows){type=row.asset_type||type;lastUpdated=row.date||lastUpdated;const amount=safeNumber(row.amount_invested),out=row.transaction_type==="sell"||row.transaction_type==="withdrawal",valuation=row.transaction_type==="valuation";if(!valuation)invested+=out?-amount:amount;const explicit=safeNumber(row.current_value);if(explicit>0){estimatedValue=explicit;hasExplicitValue=true}else if(hasExplicitValue&&!valuation){estimatedValue+=out?-amount:amount}}invested=Math.max(0,invested);if(!hasExplicitValue)estimatedValue=invested;if(invested===0&&rows.some(r=>r.transaction_type==="sell"||r.transaction_type==="withdrawal"))estimatedValue=Math.max(0,estimatedValue);const currentValue=Math.max(0,estimatedValue);if(invested<=0&&currentValue<=0)continue;assets.push({name,type,invested,currentValue,gainLoss:currentValue-invested,lastUpdated})}assets.sort((a,b)=>b.currentValue-a.currentValue);const investedTotal=assets.reduce((s,a)=>s+a.invested,0),currentValue=assets.reduce((s,a)=>s+a.currentValue,0),allocation:Record<string,number>={};for(const asset of assets)allocation[asset.type]=(allocation[asset.type]||0)+asset.currentValue;return{investedTotal,currentValue,gainLoss:currentValue-investedTotal,allocation,activeAssets:assets.length,assets}}
export function percentChange(current:number,previous:number):number|null{if(previous===0)return current===0?0:null;return((current-previous)/previous)*100}
