"use client";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { PageState } from "@/components/PageState";
import { useNudgeData } from "@/lib/client/useNudgeData";
import { apiPost } from "@/lib/client/api";

interface Status { aiConfigured:boolean; automationBridgeConfigured:boolean; spreadsheetUrl?:string; demo:boolean }
export default function SettingsPage(){
 const {data,loading,error,refresh}=useNudgeData();const s=data?.snapshot;const [name,setName]=useState("");const [currency,setCurrency]=useState("INR");const [income,setIncome]=useState("");const [essential,setEssential]=useState("");const[investTarget,setInvestTarget]=useState("");const[primaryGoal,setPrimaryGoal]=useState("");const [horizon,setHorizon]=useState("long");const [comfort,setComfort]=useState("medium");const [priority,setPriority]=useState("balanced");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [status,setStatus]=useState<Status|null>(null);
 useEffect(()=>{if(!s)return;setName(s.settings.display_name||"");setCurrency(s.settings.currency||"INR");setIncome(s.settings.monthly_income_target||"");setEssential(s.settings.essential_expenses||"");setInvestTarget(s.settings.monthly_investment_target||"");setPrimaryGoal(s.settings.primary_goal||"");setHorizon(s.settings.investment_horizon||"long");setComfort(s.settings.investor_volatility||"medium");setPriority(s.settings.investor_priority||"balanced")},[s]);
 useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(setStatus).catch(()=>undefined)},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{await apiPost("/api/settings",{display_name:name,currency,monthly_income_target:Number(income||0),essential_expenses:Number(essential||0),monthly_investment_target:Number(investTarget||0),primary_goal:primaryGoal,horizon,volatilityComfort:comfort,priority});setMessage("Settings saved. 🌿");await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Could not save.")}finally{setBusy(false)}}
 async function reshare(){setBusy(true);try{const r=await apiPost<any>("/api/settings",{reshareAutomation:true});setMessage(r.automationShared?"Year-end automation access refreshed.":"Service-account bridge is not configured yet.")}finally{setBusy(false)}}
 return <AppShell name={s?.settings.display_name||"you"} spreadsheetUrl={data?.spreadsheetUrl} demo={data?.demo} onRefresh={refresh}><PageState loading={loading} error={error}>{s&&<>
  <div className="page-head"><div><span className="eyebrow">Control and transparency</span><h1>Your Nudge settings.</h1><p>Your financial source of truth remains your Google Sheet.</p></div>{data?.spreadsheetUrl&&data.spreadsheetUrl!=="#"&&<a className="primary small" target="_blank" rel="noreferrer" href={data.spreadsheetUrl}>Open Google Sheet ↗</a>}</div>
  <div className="money-top"><section className="card"><span className="eyebrow">Personal context</span><h2>Numbers Nudge uses for context</h2><form className="form-stack" onSubmit={save}><div className="field-row"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="INR">INR · ₹</option></select></label></div><div className="field-row"><label>Typical monthly income ₹<input inputMode="decimal" value={income} onChange={e=>setIncome(e.target.value)}/></label><label>Essential monthly expenses ₹<input inputMode="decimal" value={essential} onChange={e=>setEssential(e.target.value)}/></label></div><div className="field-row"><label>Monthly investing target ₹<input inputMode="decimal" value={investTarget} onChange={e=>setInvestTarget(e.target.value)} placeholder="Optional"/></label><label>Primary goal<input value={primaryGoal} onChange={e=>setPrimaryGoal(e.target.value)} placeholder="Emergency fund, trip, wealth…"/></label></div><div className="field-row"><label>Investment horizon<select value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="short">Under 3 years</option><option value="medium">3–7 years</option><option value="long">7+ years</option></select></label><label>Market-fluctuation comfort<select value={comfort} onChange={e=>setComfort(e.target.value)}><option value="low">Low</option><option value="medium">Moderate</option><option value="high">High</option></select></label></div><label>Investing priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="preserve">Preserve</option><option value="balanced">Balanced</option><option value="growth">Growth</option></select></label><button className="primary wide" disabled={busy}>{busy?"Saving…":"Save settings"}</button>{message&&<p className="helper">{message}</p>}</form></section>
   <section className="card"><span className="eyebrow">System health</span><h2>What is connected</h2><div className="quest-list"><div className="quest-item done"><span className="quest-check">✓</span><div><b>Google Sheets source of truth</b><small>{data?.demo?"Demo data only in this preview":"Your Nudge Finance file lives in your Google Drive."}</small></div></div><div className={`quest-item ${status?.aiConfigured?"done":""}`}><span className="quest-check">{status?.aiConfigured?"✓":"·"}</span><div><b>Gemini reflection layer</b><small>{status?.aiConfigured?"Configured. Raw ledger is still not sent to AI.":"Optional. Natural-language basics and rule-based insights still work without it."}</small></div></div><div className={`quest-item ${status?.automationBridgeConfigured?"done":""}`}><span className="quest-check">{status?.automationBridgeConfigured?"✓":"·"}</span><div><b>December 31 server bridge</b><small>{status?.automationBridgeConfigured?"Service account is configured for unattended Wrapped preparation.":"Optional. Without it, Wrapped generates when you next open Nudge."}</small></div></div></div>{status?.automationBridgeConfigured&&!data?.demo&&<button className="secondary" style={{marginTop:14}} onClick={reshare} disabled={busy}>Refresh Sheet automation access</button>}</section>
  </div>
 </>}</PageState></AppShell>
}
