"use client";
import { FormEvent, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { PageState } from "@/components/PageState";
import { MoneyRiver } from "@/components/MoneyRiver";
import { useNudgeData } from "@/lib/client/useNudgeData";
import { apiPost } from "@/lib/client/api";
import { percentChange } from "@/lib/core/finance";
import { indiaDateParts } from "@/lib/core/date";

const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;
const tones=["#fff0df","#e9f4fb","#f0ebfb","#f7f0d9","#e9f6ec","#f9e9ed"];
const icons:Record<string,string>={Food:"🍽️",Travel:"🚕",Shopping:"🛍️",Living:"🏠",Bills:"💡",Fun:"🎉",Health:"🌿",Learning:"📚",Gifts:"🎁",Personal:"✨",Other:"✨"};
const budgetCategories=["Food","Travel","Shopping","Living","Bills","Fun","Health","Learning","Gifts","Personal","Other"];

export default function MoneyPage(){
 const current=indiaDateParts().month; const [month,setMonth]=useState(current); const {data,loading,error,refresh}=useNudgeData(month); const s=data?.snapshot;
 const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState(""); const [asking,setAsking]=useState(false);
 const [settling,setSettling]=useState<string|null>(null); const [settleAmounts,setSettleAmounts]=useState<Record<string,string>>({});
 const [budgetCategory,setBudgetCategory]=useState("Food"); const [budgetAmount,setBudgetAmount]=useState(""); const [budgetBusy,setBudgetBusy]=useState(false); const [budgetMessage,setBudgetMessage]=useState("");
 const change=s?percentChange(s.finance.personalSpending,s.previousFinance.personalSpending):0;
 const categoryEntries=useMemo(()=>s?Object.entries(s.finance.categoryTotals).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]):[],[s]);
 async function ask(e:FormEvent){e.preventDefault();if(!question.trim())return;setAsking(true);try{const r=await apiPost<{answer:string}>("/api/insights",{question,month});setAnswer(r.answer)}catch(e){setAnswer(e instanceof Error?e.message:"Could not answer right now.")}finally{setAsking(false)}}
 async function settle(id:string,remaining:number,forcedAmount?:number){setSettling(id);try{const raw=settleAmounts[id];const amount=forcedAmount??(raw?Number(raw):remaining);await apiPost("/api/splits/settle",{splitId:id,amount});setSettleAmounts(v=>({...v,[id]:""}));await refresh()}catch(e){setAnswer(e instanceof Error?e.message:"Could not settle this split.")}finally{setSettling(null)}}
 async function saveBudget(e:FormEvent){e.preventDefault();const amount=Number(budgetAmount);if(!Number.isFinite(amount)||amount<=0){setBudgetMessage("Enter a positive monthly amount.");return}setBudgetBusy(true);setBudgetMessage("");try{await apiPost("/api/budgets",{month,category:budgetCategory,budget_amount:amount});setBudgetAmount("");setBudgetMessage(`${budgetCategory} budget saved for ${month}. 🌿`);await refresh()}catch(e){setBudgetMessage(e instanceof Error?e.message:"Could not save budget.")}finally{setBudgetBusy(false)}}
 return <AppShell name={s?.settings.display_name||"you"} spreadsheetUrl={data?.spreadsheetUrl} demo={data?.demo} onRefresh={refresh}><PageState loading={loading} error={error}>{s&&<>
  <div className="page-head"><div><span className="eyebrow">Money without the guilt spiral</span><h1>Your money, in context.</h1><p>Cash outflow and your actual personal expense stay separate—especially when friends are involved.</p></div><label className="date-pill">Month&nbsp; <input aria-label="Money month" type="month" value={month} onChange={e=>setMonth(e.target.value)} style={{border:0,padding:0,width:120,background:"transparent"}}/></label></div>
  <div className="money-top"><section className="card"><div className="section-title"><h2>Money river</h2><span>{month}</span></div><MoneyRiver categories={s.finance.categoryTotals} income={s.finance.income}/><div className="stats-grid"><div className="stat-card"><span className="icon">💸</span><strong>{money(s.finance.personalSpending)}</strong><small>your actual spending</small></div><div className="stat-card"><span className="icon">🌱</span><strong>{money(s.finance.futureAllocation)}</strong><small>saved + invested</small></div><div className="stat-card"><span className="icon">🤝</span><strong>{money(s.openReceivable)}</strong><small>friends owe you overall</small></div><div className="stat-card"><span className="icon">☀️</span><strong>{s.finance.noSpendDays}</strong><small>no-spend days in period</small></div></div></section>
   <section className="card"><span className="eyebrow">This month</span><div className="big-number">{money(s.finance.personalSpending)}</div><div className={`delta ${change!=null&&change<=0?"good":"soft"}`}>{change==null?"No comparable previous month yet":`${Math.abs(change).toFixed(0)}% ${change<=0?"lower":"higher"} than last month`}</div><div className="spacer-18"/><div className="nudge-note"><span>💛</span><div><b>Personal expense ≠ bank outflow</b><br/><span>Nudge removes friends’ shares from personal spending and tracks those shares as receivables instead.</span></div></div><div className="spacer-18"/><div className="stats-grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="stat-card"><strong>{money(s.finance.cashOutflow)}</strong><small>cash outflow</small></div><div className="stat-card"><strong>{money(s.finance.cashLeft)}</strong><small>recorded income less spend/save/invest</small></div></div></section>
  </div>
  <div className="spacer-18"/>
  <section className="card"><div className="section-title"><h2>Where your money wandered</h2><span>Personal shares only</span></div>{categoryEntries.length?<div className="money-orbs">{categoryEntries.map(([name,value],i)=><div key={name} className="money-orb" style={{"--tone":tones[i%tones.length]} as React.CSSProperties}><span>{icons[name]||"✨"} {name}</span><strong>{money(value)}</strong><small>{s.finance.personalSpending>0?`${((value/s.finance.personalSpending)*100).toFixed(0)}% of personal spend`:"Net period total is zero"}</small></div>)}</div>:<div className="empty-card compact"><span>🌊</span><p>Log an expense and the category landscape will appear here.</p></div>}</section>
  <div className="spacer-18"/>
  <div className="money-top"><section className="card"><div className="section-title"><h2>Spending gardens</h2><span>{month} budgets</span></div><p className="helper">A budget is a boundary for awareness, not a grade. Crossing it simply gives you context for the rest of the month.</p><form className="budget-form" onSubmit={saveBudget}><select aria-label="Budget category" value={budgetCategory} onChange={e=>setBudgetCategory(e.target.value)}>{budgetCategories.map(c=><option key={c}>{c}</option>)}</select><input aria-label="Budget amount" inputMode="decimal" value={budgetAmount} onChange={e=>setBudgetAmount(e.target.value)} placeholder="Monthly ₹"/><button className="primary small" disabled={budgetBusy}>{budgetBusy?"Saving…":"Plant budget"}</button></form>{budgetMessage&&<p className="helper">{budgetMessage}</p>}{s.budgetProgress.length?<div className="budget-garden">{s.budgetProgress.map(b=>{const pct=Math.min(100,Math.max(4,b.progress));const scale=.55+(pct/220);return <article className={`budget-pot ${b.status}`} key={b.id}><div className="budget-plant" style={{"--growth-scale":scale} as React.CSSProperties}><span>🌿</span></div><div><b>{b.category}</b><strong>{money(b.spent)} <small>of {money(b.budget_amount)}</small></strong><p>{b.status==="over"?`${money(Math.abs(b.remaining))} above the plan — useful context, not a failure.`:b.status==="near"?`${money(Math.max(0,b.remaining))} of breathing room remains.`:`${money(Math.max(0,b.remaining))} still available.`}</p></div></article>})}</div>:<div className="empty-card compact"><span>🪴</span><p>Plant a category budget above and Nudge will grow a small visual around it.</p></div>}</section>
   <section className="ask-box"><span className="eyebrow">Ask Nudge</span><h2>Ask the question you actually care about.</h2><p className="helper">Nudge calculates with code first. AI only receives safe aggregate numbers—not your raw transaction ledger.</p><form onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Why did I spend more this month?"/><button className="primary" disabled={asking}>{asking?"Thinking…":"Ask"}</button></form>{answer&&<div className="ask-answer">{answer}</div>}</section>
  </div>
  <div className="spacer-18"/>
  <section className="card"><div className="section-title"><h2>Splits with friends</h2><span>{money(s.openReceivable)} open overall · settlements are not income</span></div>{s.splits.filter(x=>x.status!=="settled").length?<div className="split-grid">{s.splits.filter(x=>x.status!=="settled").map(x=>{const remain=Math.max(0,x.their_share-x.settled_amount);return <article className="split-card" key={x.id}><div className="person"><span>{x.person.slice(0,1).toUpperCase()}</span><b>{money(remain)}</b></div><h4>{x.person}</h4><p>{x.status==="partial"?`${money(x.settled_amount)} already returned.`:"Waiting to settle."}</p><div className="settle-row"><input aria-label={`Amount received from ${x.person}`} inputMode="decimal" value={settleAmounts[x.id]||""} onChange={e=>setSettleAmounts(v=>({...v,[x.id]:e.target.value}))} placeholder={`₹${Math.round(remain)}`}/><button className="mini-button" disabled={settling===x.id} onClick={()=>settle(x.id,remain)}>{settling===x.id?"Saving…":"Record return"}</button></div><button className="text-action" disabled={settling===x.id} onClick={()=>void settle(x.id,remain,remain)}>Settle full balance</button></article>})}</div>:<div className="empty-card compact"><span>🤝</span><h3>All settled</h3><p>No pending friend balances right now.</p></div>}</section>
  <div className="spacer-18"/>
  <section className="card"><div className="section-title"><h2>Recent money moments</h2><span>{s.finance.transactionCount} records this month</span></div><div className="timeline">{s.transactions.filter(t=>t.date.startsWith(month)).slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).slice(0,12).map(t=><div className="tx-row" key={t.id}><div className="tx-icon">{t.type==="investment"?"🌱":t.type==="saving"?"🛡️":t.type==="income"?"☀️":t.type==="investment_withdrawal"?"🌾":icons[t.category]||"✨"}</div><div><strong>{t.description||t.category}</strong><small>{t.date} · {t.category}{t.split_amount?` · ${money(t.split_amount)} belongs to friends`:""}</small></div><div className="tx-amount">{t.type==="income"||t.type==="refund"||t.type==="investment_withdrawal"?"+":"−"}{money(t.type==="expense"?(t.personal_amount??t.amount):t.amount)}</div></div>)}</div></section>
 </>}</PageState></AppShell>
}
