"use client";
import { FormEvent, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { PageState } from "@/components/PageState";
import { GoalJourney } from "@/components/GoalJourney";
import { useNudgeData } from "@/lib/client/useNudgeData";
import { apiPost } from "@/lib/client/api";

const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;
export default function GoalsPage(){
 const {data,loading,error,refresh}=useNudgeData(); const s=data?.snapshot; const [goal,setGoal]=useState(""); const [target,setTarget]=useState(""); const [type,setType]=useState("Personal"); const [monthly,setMonthly]=useState(""); const [busy,setBusy]=useState(false); const [contrib,setContrib]=useState<Record<string,string>>({});
 async function add(e:FormEvent){e.preventDefault();setBusy(true);try{await apiPost("/api/goals",{goal,goal_type:type,target_amount:Number(target),monthly_target:Number(monthly||0)});setGoal("");setTarget("");setMonthly("");await refresh()}finally{setBusy(false)}}
 async function contribute(id:string){const amount=Number(contrib[id]||0);if(!amount)return;setBusy(true);try{await apiPost("/api/goals/contribute",{goalId:id,amount});setContrib({...contrib,[id]:""});await refresh()}finally{setBusy(false)}}
 return <AppShell name={s?.settings.display_name||"you"} spreadsheetUrl={data?.spreadsheetUrl} demo={data?.demo} onRefresh={refresh}><PageState loading={loading} error={error}>{s&&<>
  <div className="page-head"><div><span className="eyebrow">Goals that mean something</span><h1>Turn money into journeys.</h1><p>A goal is not just a percentage—it is something your money is helping make possible.</p></div><span className="date-pill">⚑ {s.goalProgress.filter(g=>g.status==="active").length} active</span></div>
  <div className="money-top"><section className="card"><div className="section-title"><h2>Your journeys</h2><span>Contributions are also written as Savings transactions</span></div><div className="goal-list">{s.goalProgress.map(g=><div key={g.id}><GoalJourney name={g.goal} progress={g.progress} current={g.current_amount} target={g.target_amount} months={g.monthsRemaining} type={g.goal_type}/>{g.status!=="completed"&&<div style={{display:"flex",gap:8,margin:"8px 0 18px"}}><input inputMode="decimal" placeholder="Contribution ₹" value={contrib[g.id]||""} onChange={e=>setContrib({...contrib,[g.id]:e.target.value})}/><button className="mini-button" disabled={busy} onClick={()=>contribute(g.id)}>Add to goal</button></div>}{g.status==="completed"&&<p className="helper">✨ Goal reached. Let yourself enjoy that.</p>}</div>)}</div></section>
   <section className="card"><span className="eyebrow">Start another journey</span><h2>What is Future You planning?</h2><form className="form-stack" onSubmit={add}><label>Goal name<input required value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Emergency fund, trip, course…"/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option>Safety</option><option>Experience</option><option>Learning</option><option>Home</option><option>Long-term Wealth</option><option>Personal</option></select></label><div className="field-row"><label>Target ₹<input required inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Monthly pace ₹<input inputMode="decimal" value={monthly} onChange={e=>setMonthly(e.target.value)} placeholder="Optional"/></label></div><button className="primary wide" disabled={busy}>{busy?"Saving…":"Create goal →"}</button></form><div className="nudge-note"><span>🛡️</span><div><b>Emergency fund tip</b><br/><span>Nudge can show months of essential-expense coverage using the monthly essential expense you set. It does not prescribe a universal target.</span></div></div></section></div>
  {s.goalProgress.length>0&&<><div className="spacer-18"/><section className="card"><div className="section-title"><h2>Goal landscape</h2><span>Where recorded goal money currently sits</span></div><div className="money-orbs">{s.goalProgress.map((g,i)=><div className="money-orb" key={g.id} style={{"--tone":["#e9f6ec","#fff0df","#e9f4fb","#f0ebfb"][i%4]} as React.CSSProperties}><span>{g.goal_type}</span><strong>{money(g.current_amount)}</strong><small>{money(g.remaining)} remaining</small></div>)}</div></section></>}
 </>}</PageState></AppShell>
}
